### ISSUE TITLE
States with having consecutive values 

### ISSUE THREAD

**Issue by Urvek** [JavaCardSpot-dev/cryptsetup-javacard#1]
The applet can be in 3 states 
STATE_IDLE 0
STATE_KEY_ESTABILISHED 1
STATE_AUTHENTICATED 2

These states are having very sort hamming distance and by fault induction attack, attacker can modify the value of state and can perform sensitive operations.

**Comment by hiteshlilhare** [comment]
Updated the state constants to have significant hamming distance among themselves.

**Comment by Urvek** [comment]
Pls describe the new values changed with consecutive state values

**Comment by Urvek** [comment]
STATE_IDLE = (short)0x4CCC;
STATE_KEY_ESTABILISHED = (short)0x5555;
STATE_AUTHENTICATED = (short)0x2AAA;
